### ISSUE TITLE
swi-mqtt-pack not known to swi-prolog.org

### ISSUE THREAD

**Issue by Anniepoo** [olsky/swi-mqtt-pack#1]
Your pack is cool, and already appears to be a pack. 

Please submit to swi-prolog.org central pack directory.

http://www.swi-prolog.org/howto/Pack.html

This allows, eg. crazy prolog programmers making robotic snails like myself to install by canonical name, rather than a more volatile github URL.

**Comment by olsky** [comment]
Hello Anne, 

thank you for your feedback and interest. 

I have tried to place is in the pack registry, here it is: http://www.swi-prolog.org/pack/list?p=mqtt

Let me check if it is still available from swipl...

**Comment by Anniepoo** [comment]
I'm an imbecile. It's there. I searched for swi-mqtt or something. 

closing, thanks
